### ISSUE TITLE
Amazon support

### ISSUE THREAD

**Issue by SalavatR** [AppLovin/AppLovin-MAX-Defold#8]
Hi!
can you please add amazon support?

also we have plugin for applovin, and feature to enable/disable adapters
https://github.com/HGPoint/defold-maxsdk/blob/master/def_applovin_maxsdk/manifests/android/build.gradle 
to enable add "IronSourceAdapter = 1" in game.project file
the only issue is to update ios resources

**Comment by wootaejeon** [comment]
Hi @SalavatR, we recommend that you create a separate `Podfile` / `build.gradle` file to add third-party SDKs (and the necessary open source adapters) so that you have full control over their integration. Please refer to [Preparing Mediated Networks](https://dash.applovin.com/documentation/mediation/defold/mediation-adapters/android) for more information.
